#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# GHOST-SWARM GLOBAL DEPLOYMENT BOOTSTRAP
# =============================================================================
# Auto-installs dependencies, clones the repository, and starts the swarm
# as a background daemon on a remote Linux server (Render, Oracle Cloud,
# AWS EC2, DigitalOcean, etc.)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/YOUR_ORG/ghost-swarm/main/deploy_bootstrap.sh | bash
#
# Or locally:
#   bash deploy_bootstrap.sh [--node-id my-node-1] [--swarm-secret mysecret]
#
# Env vars (all optional):
#   SWARM_SECRET      — shared HMAC secret for mesh authentication
#   NODE_ID           — unique node identifier (default: hostname)
#   MANAGER_PORT      — dashboard port (default: 7860)
#   DHT_ENABLED       — enable Kademlia DHT (default: true)
#   DHT_PORT          — UDP port for DHT (default: 8468)
# =============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()  { echo -e "${CYAN}[STEP]${NC} $1"; }


# ---- Config ----------------------------------------------------------------
SWARM_SECRET="${SWARM_SECRET:-$(openssl rand -hex 32)}"
NODE_ID="${NODE_ID:-$(hostname)-ghost}"
MANAGER_PORT="${MANAGER_PORT:-7860}"
DHT_ENABLED="${DHT_ENABLED:-true}"
DHT_PORT="${DHT_PORT:-8468}"
REPO_URL="${REPO_URL:-https://github.com/anomalyco/Decentralized-AI-Agent.git}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/ghost-swarm}"
BRANCH="${BRANCH:-main}"
TRANSMISSION_MODE="${TRANSMISSION_MODE:-downlink}"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║        GHOST-SWARM GLOBAL DEPLOYMENT BOOTSTRAP         ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
log_info "Node ID:       $NODE_ID"
log_info "Manager Port:  $MANAGER_PORT"
log_info "DHT Enabled:   $DHT_ENABLED (port $DHT_PORT)"
log_info "Install Dir:   $INSTALL_DIR"
log_info "Transmission:  $TRANSMISSION_MODE"
log_info "Swarm Secret:  ${SWARM_SECRET:0:8}... (set SWARM_SECRET env var to persist)"
echo ""


# ---- Step 1: Install system dependencies ----------------------------------
log_step "1/6 — Installing system dependencies..."

if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq python3 python3-pip python3-venv git curl netcat-openbsd 2>/dev/null
elif command -v yum &>/dev/null; then
    sudo yum install -y python3 python3-pip git curl nc 2>/dev/null
elif command -v apk &>/dev/null; then
    apk add --no-cache python3 py3-pip git curl netcat-openbsd 2>/dev/null
else
    log_warn "Unknown package manager — assuming Python 3 is available"
fi

python3 --version
pip3 --version 2>/dev/null || python3 -m pip --version


# ---- Step 2: Clone repository --------------------------------------------
log_step "2/6 — Cloning ghost-swarm repository..."

if [ -d "$INSTALL_DIR" ]; then
    log_info "Directory $INSTALL_DIR exists — pulling latest..."
    cd "$INSTALL_DIR"
    git pull origin "$BRANCH" 2>/dev/null || log_warn "Git pull failed, using existing"
else
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi


# ---- Step 3: Install Python dependencies ----------------------------------
log_step "3/6 — Installing Python dependencies..."

python3 -m venv "$INSTALL_DIR/venv" 2>/dev/null || virtualenv "$INSTALL_DIR/venv" 2>/dev/null || log_warn "venv creation failed"
if [ -f "$INSTALL_DIR/venv/bin/activate" ]; then
    source "$INSTALL_DIR/venv/bin/activate"
    log_info "Virtual environment activated"
fi

pip install --quiet --upgrade pip setuptools wheel 2>/dev/null
if [ -f requirements.txt ]; then
    pip install --quiet -r requirements.txt 2>&1 | tail -3
    log_info "Core dependencies installed"
fi

# Install optional swarm dependencies (best-effort)
pip install --quiet numpy 2>/dev/null || log_warn "numpy not installed (satellite features degraded)"
pip install --quiet kademlia 2>/dev/null || log_warn "kademlia not installed (DHT degraded — relay mode active)"
pip install --quiet httpx cryptography 2>/dev/null || true

# Install reedsolo for satellite FEC (best-effort)
pip install --quiet reedsolo 2>/dev/null || log_warn "reedsolo not installed (FEC disabled, raw fragments)"


# ---- Step 4: Configure environment ---------------------------------------
log_step "4/6 — Configuring swarm environment..."

cat > "$INSTALL_DIR/.env" << EOF
# Ghost-Swarm Node Configuration (auto-generated by bootstrap)
NODE_ID=$NODE_ID
MANAGER_PORT=$MANAGER_PORT
SWARM_SECRET=$SWARM_SECRET
DHT_ENABLED=$DHT_ENABLED
DHT_PORT=$DHT_PORT
TRANSMISSION_MODE=$TRANSMISSION_MODE
ENABLE_DHT=$([[ "$DHT_ENABLED" == "true" ]] && echo "1" || echo "0")
PUBLIC_URL=http://$(hostname -I 2>/dev/null | awk '{print $1}'):$MANAGER_PORT
EOF

log_info ".env written to $INSTALL_DIR/.env"
log_warn "IMPORTANT: Set SWARM_SECRET to the same value on ALL swarm nodes"
echo "  export SWARM_SECRET=$SWARM_SECRET"


# ---- Step 5: Create systemd service (if available) -----------------------
log_step "5/6 — Creating startup service..."

SERVICE_NAME="ghost-swarm"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

if command -v systemctl &>/dev/null; then
    sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=Ghost-Swarm Global Mesh Node
After=network.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=$INSTALL_DIR/venv/bin/python -m uvicorn manager:app --host 0.0.0.0 --port \$MANAGER_PORT
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME" 2>/dev/null || true
    sudo systemctl restart "$SERVICE_NAME" 2>/dev/null || true
    log_info "systemd service created: $SERVICE_FILE"
else
    log_warn "systemd not available — creating background process fallback"

    # Create a supervisor-style start script
    cat > "$INSTALL_DIR/start_swarm.sh" << 'SHEOF'
#!/usr/bin/env bash
cd "$(dirname "$0")"
source venv/bin/activate 2>/dev/null || true
export $(cat .env | xargs) 2>/dev/null || true
exec python -m uvicorn manager:app --host 0.0.0.0 --port ${MANAGER_PORT:-7860}
SHEOF
    chmod +x "$INSTALL_DIR/start_swarm.sh"

    # Start in background with nohup
    nohup "$INSTALL_DIR/start_swarm.sh" > "$INSTALL_DIR/swarm.log" 2>&1 &
    log_info "Background swarm process started (PID: $!)"
fi


# ---- Step 6: Verify deployment -------------------------------------------
log_step "6/6 — Verifying swarm deployment..."

sleep 5
if command -v ss &>/dev/null; then
    LISTENING=$(ss -tlnp | grep ":$MANAGER_PORT" | head -1)
elif command -v netstat &>/dev/null; then
    LISTENING=$(netstat -tlnp 2>/dev/null | grep ":$MANAGER_PORT" | head -1)
else
    LISTENING="(cannot check — need ss or netstat)"
fi

if [ -n "$LISTENING" ]; then
    log_info "Swarm dashboard is LISTENING on port $MANAGER_PORT"
else
    log_warn "Port $MANAGER_PORT not yet listening — check logs"
fi

# Also start the passive satellite listener and DHT mesh node
cd "$INSTALL_DIR"
nohup python -c "
import asyncio
import os
os.environ['MANAGER_PORT'] = os.getenv('MANAGER_PORT', '7860')
os.environ['SWARM_SECRET'] = os.getenv('SWARM_SECRET', '$SWARM_SECRET')

async def start_all():
    # Start DHT mesh node
    try:
        from mesh import run_mesh_node
        asyncio.create_task(run_mesh_node(port=int(os.getenv('DHT_PORT', '8468'))))
        print('[DHT] Mesh node started')
    except Exception as e:
        print(f'[DHT] Not available: {e}')

    # Start passive satellite listener (no SDR needed — software mode)
    try:
        import stealth_beyond_sat
        asyncio.create_task(stealth_beyond_sat.start_passive_listener(
            force_active=True,
            carrier_mhz=10723.0,
        ))
        print('[SATELLITE] Passive listener started (software mode)')
    except Exception as e:
        print(f'[SATELLITE] Not available: {e}')

    # Keep alive
    while True:
        await asyncio.sleep(3600)

asyncio.run(start_all())
" > "$INSTALL_DIR/swarm_daemon.log" 2>&1 &
DAEMON_PID=$!
echo $DAEMON_PID > "$INSTALL_DIR/swarm_daemon.pid"
log_info "Background daemon PID: $DAEMON_PID (satellite + DHT mesh)"


echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        GHOST-SWARM DEPLOYMENT COMPLETE                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}Dashboard:${NC}       http://$(hostname -I 2>/dev/null | awk '{print $1}'):$MANAGER_PORT"
echo -e "${CYAN}Health:${NC}          curl http://localhost:$MANAGER_PORT/api/status"
echo -e "${CYAN}Security:${NC}        curl http://localhost:$MANAGER_PORT/api/swarm/security"
echo -e "${CYAN}GhostSignal:${NC}     curl http://localhost:$MANAGER_PORT/api/ghostsignal/status"
echo ""
echo -e "${YELLOW}To share secret with new nodes:${NC}"
echo "  export SWARM_SECRET=$SWARM_SECRET"
echo ""
echo -e "${YELLOW}To check logs:${NC}"
echo "  sudo journalctl -u $SERVICE_NAME -f   # systemd"
echo "  tail -f $INSTALL_DIR/swarm.log          # nohup"
echo ""
echo -e "${YELLOW}To add a remote peer:${NC}"
echo "  export SWARM_SECRET=$SWARM_SECRET"
echo "  python -c \"from swarm_security import *; print(ghost_encrypt_packet('{\\\"peer\\\":\\\"$(hostname -I | awk '{print $1}')\\\"}'))\""
echo ""
